#服务配置
server:
  port: 9001
#Spring配置

spring:
  #1.应用配置
  application:
    name: hrm-company
  #2.数据库连接池的配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hrm?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
#mybatis-plus的配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: com.hrm.entity.company
  global-config:
    db-config:
      id-type: ASSIGN_ID